#!/bin/bash

if [ `whoami` != "root" ]; then
	echo "You must run this script as root."
	exit 1
fi

# Make sure wget is installed.
yum -y install wget

# Download the bootstrapper script.
wget --no-check-certificate -O go https://raw.github.com/ausaccessfed/aasc/master/go

# Download the yum repository configuration.
wget --no-check-certificate -O aasc.repo https://raw.github.com/ausaccessfed/aasc/master/aasc.repo

# Set appropriate permissions to run the bootstrapper.
chmod 755 aasc.repo
chmod 700 go

# Configure yum.
cp -p aasc.repo /etc/yum.repos.d

# Run the bootstrapper
./go
